[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "{{ homu.gh.access_token }}"

# A GitHub oauth application for this instance of homu:
app_client_id = "{{ homu.gh.oauth_id }}"
app_client_secret = "{{ homu.gh.oauth_secret }}"

[git]
local_git = {{ homu.git.local_git }}
ssh_key = """{{ homu.git.ssh_key}}"""
status_based_exemption = {{ homu.git.local_git }}

[web]
port = {{ homu.web.port }}
{% if homu.web.secret %}
secret = "{{ homu.web.secret }}"
{% endif %}

{% for repo in homu.repos %}
[repo.'{{ repo.slug }}']

# github.com/<owner>/<name>
owner = "{{ repo.owner }}"
name = "{{ repo.name }}"

# who has r+ rights?
reviewers = {{ homu.reviewers }}

[repo.'{{ repo.slug }}'.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = "{{ homu.gh.webhook_secret }}"

{% if repo.appveyor %}
[repo.'{{ repo.slug }}'.status.appveyor]

context = "continuous-integration/appveyor/branch"
{% endif %}

{% if repo.travis %}
[repo.'{{ repo.slug }}'.status.travis]

context = "continuous-integration/travis-ci/push"
{% endif %}

{% endfor %}
